package com.leoita.controller;

import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
public class WelcomeController {

    @GetMapping("/welcome")
    public String sayWelcome() {
        return "Welcome from Spring Application with Security";
    }
    /*
    when we open localHost:8080/welcome:
    without spring security dependency the message will be displayed
    with spring security dependency the page will require to login.
    default username is user and password is the one generated by Spring APP in the console,
    Using generated security password: ...
    You can define your user and password in the application.properties
    */

}
